"""Centralized defaults for the public full-pipeline entrypoint."""
from __future__ import annotations

from typing import Any, Dict


def public_full_pipeline_defaults() -> Dict[str, Any]:
    """Return the internal defaults behind the slim public full-pipeline CLI."""

    return {
        "mhr_py": "mhr70.py",
        "toml_sections": None,
        "detector_name": "sam3",
        "segmentor_name": "sam3",
        "fov_name": "moge2",
        "detector_path": "",
        "segmentor_path": "",
        "fov_path": "",
        "bbox_thresh": 0.8,
        "use_mask": False,
        "debug_inference": False,
        "save_mhr_params": False,
        "person_select_strategy": "largest_bbox",
        "person_index": 0,
        "specialized_hand_source": "precomputed",
        "specialized_hand_device": "cuda",
        "specialized_hand_detector_conf": 0.3,
        "specialized_hand_rescale_factor": 2.5,
        "specialized_hand_wrist_max_dist_px": 140.0,
        "replace_wrist_with_specialized": False,
        "specialized_hand_debug_vis": False,
        "specialized_hand_debug_dirname": "specialized_hand_debug",
        "specialized_hand_verbose": False,
        "wilor_pretrained_dir": "",
        "wilor_repo_id": "warmshao/WiLoR-mini",
        "skip_inference": False,
        "skip_triangulation": False,
        "triangulated_name": "triangulated.npz",
        "optimized_name": "opt_out.npy",
        "normalized": False,
        "pixel": False,
        "invert_extrinsics": False,
        "lm_iters": 25,
        "lm_lambda": 1e-3,
        "lm_eps": 1e-4,
        "score_type": "median",
        "huber_delta": 10.0,
        "inlier_thresh": 30.0,
        "robust_lm": False,
        "robust_lm_delta": 10.0,
        "save_triangulation_debug": False,
        "iters": 200,
        "lr": 5e-2,
        "with_scale": True,
        "huber_m": 0.03,
        "w_pose_reg": 1e-3,
        "w_hand_reg": 1e-3,
        "w_temporal": 3e-3,
        "temporal_init_blend": 0.7,
        "fixed_lower_body_pose_frame_idx": None,
        "fixed_lower_body_pose_cam": "front",
        "optimize_hand_pose": True,
        "use_anchor_similarity": True,
        "bad_loss_threshold": 3e-3,
        "bad_data_loss_threshold": 2.5e-3,
        "bad_loss_growth_ratio": 1.5,
        "min_valid_points": 6,
        "zero_weight_strategy": "uniform_finite",
        "topk_print": 10,
        "save_opt_debug": False,
        "max_stale_temporal_frames": 40,
        "max_edge_recovery_copy_span": 15,
        "enable_smoothing": True,
        "smoothing_alpha": 0.65,
        "smoothing_median_window": 5,
        "smoothing_outlier_sigma": 3.5,
        "smoothed_name": "opt_out_smoothed.npy",
        "sequence_mp4_name": "sequence_debug.mp4",
        "sequence_fps": 20,
        "save_summary_json": True,
    }
